apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: simplecrs.romeo.org
spec:
  group: romeo.org
  names:
    plural: simplecrs
    singular: simplecr
    kind: SimpleCr
    shortNames:
    - scr
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              appId:
                type: string
              environmentType:
                type: string
                enum:
                - dev
                - test
                - prod
              replicas:
                type: integer
                minimum: 1
            required: ["appId", "environmentType"]
        required: ["spec"]
